### ISSUE TITLE
Alice in Wonderland external tiddler seems to be gone - causes GET request endless loop

### ISSUE THREAD

**Issue by pmario** [Jermolene/jermolene.github.io#3]
@Jermolene 

It seems the text tiddler has been replaced with: https://github.com/Jermolene/jermolene.github.io/blob/e559512e38/text/Alice%2520in%2520Wonderland.tid which seems to cause an endless loop if tiddler: https://tiddlywiki.com/#Alice%20in%20Wonderland is requested. 

See dev-tools Network tab. ... 

It seems the last build process has gone wrong. ...

**Comment by Jermolene** [comment]
Thanks @pmario, this is fixed now
