### ISSUE TITLE
[Idea] I think a TW single file archive should be created and accessible from tiddlywiki.com or tiddlywiki.org

### ISSUE THREAD

**Issue by pmario** [Jermolene/jermolene.github.io#4]
I did just create all TW version from v5.1.0 up to v5.2.5 as TiddlyWiki-5.x.y.html

Can I create a PR to host them at `tiddlywiki.<com-or-org>/archive/<filename>.html `

What do you think?

**Comment by Jermolene** [comment]
Hi @pmario yes I think it would be helpful to have an archive of old empty versions of TW.

As well as your PR, we'll also need to update the release instructions to include saving the archive version:

https://tiddlywiki.com/dev/#Releasing%20a%20new%20version%20of%20TiddlyWiki

**Comment by pmario** [comment]
I did create "doc versions" but could create empty too .. or do you want the a full `--build` which also may create static. .. But this will need a lot more time :)

I'm using the Node.js LTS version 16.13.0 ... which did throw some deprecation wanings up to I think 5.1.8 or so. .. It all worked. But with future version of node we may need to user older node versions too.

**Comment by pmario** [comment]
>As well as your PR, we'll also need to update the release instructions to include saving the archive version:
>
>https://tiddlywiki.com/dev/#Releasing%20a%20new%20version%20of%20TiddlyWiki

ahh, I see.

**Comment by pmario** [comment]
I'm not sure, if we also need to create a robots.txt ... to avoid crawlers from indexing the old stuff. .. Do you have experience here?

**Comment by Jermolene** [comment]
> I did create "doc versions" but could create empty too .. or do you want the a full `--build` which also may create static. .. But this will need a lot more time :)

I think just an icon of empty versions is sufficient. If we publish older versions of the static builds then there is a risk of Google directing people to out of date versions of the documentation.

> I'm using the Node.js LTS version 16.13.0 ... which did throw some deprecation wanings up to I think 5.1.8 or so. .. It all worked. But with future version of node we may need to user older node versions too.

Our build process is incremental; we don't need to build these archive versions as part of `build-site.sh`; once your PR is merged it will just be a matter of adding the new version to the archive at each release.

**Comment by Jermolene** [comment]
> I'm not sure, if we also need to create a robots.txt ... to avoid crawlers from indexing the old stuff. .. Do you have experience here?

If we're careful about what goes into the archive directory then I don't think it's a problem for search engines to crawl it.

**Comment by pmario** [comment]
@Jermolene ... Should the archive versions show an icon? ... Currently it's the blue one. PR follows soon

**Comment by Jermolene** [comment]
I think as far as possible the archive versions should be a snapshot of tiddlywiki.com at the moment of release, with the original content included.

Am I right in thinking that if we added a favicon.ico file then it would be overridden by the core `$:/favicon.ico` when the wiki loads?

**Comment by pmario** [comment]
If I do load **empty-x.y.z.html** from file:// uri and there is no favicon.ico file in the directory it has **no icon** in the browser. ... That's why I did ask. 

Checking tiddlywiki-5.y.z.html full version will create it's own icon. So it does not need a favicon.ico file.

**Comment by Jermolene** [comment]
> If I do load **empty-x.y.z.html** from file:// uri and there is no favicon.ico file in the directory it has **no icon** in the browser. ... That's why I did ask.

> Checking tiddlywiki-5.y.z.html full version will create it's own icon. So it does not need a favicon.ico file.

That's true. I do wonder if we shouldn't have a default favicon built into the core.

So, yes, let's save the normal blue icon as favicon.ico in the same directory.

Can you outline the directory and filename structure you're thinking of?

**Comment by pmario** [comment]
- `jermolene.github.io/archive/full/TiddlyWiki-5.1.0.html`
- `jermolene.github.io/archive/empty/empty-5.1.0.html`

The full/ dir will also have Alice...tid and 2 images, because they where created with the `--build index` target. At least "Alice in wonderland" imo is important. 

- `../full/text/Alice%20in%20Wonderland.tid`
- `../full/images/Blurry...jpg`
- `../full/images/Newnham...jpg`

**Comment by Jermolene** [comment]
Thanks @pmario that makes sense about Alice and the images. Perhaps the empty filename should be `Empty-TiddlyWiki-5.1.0.html` for consistency?
